apiVersion: apps/v1
kind: Deployment
metadata:
  name: catool-ns-ws-deployment
  namespace: catool-ns
  labels:
    app: catool-ns-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catool-ns-ws
  template:
    metadata:
      labels:
        app: catool-ns-ws
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: catool-ns-ws
          image:  132.186.17.22:5000/catool-ns:1-1-1-layers
          imagePullPolicy: IfNotPresent
          command: ["sh", "/root/docker-catool-entry"]
          args: ["ws"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: catool-ns-config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: catool-ns-data-volume
              mountPath: /app/data
            - name: catool-ns-logs-volume
              mountPath: /app/logs
          env:
            - name: CATOOL_CONFIG_FILE
              value: /app/config.yaml
      volumes:
        - name: catool-ns-config-volume
          configMap:
            name: catool-ns-config
        - name: catool-ns-data-volume
          hostPath:
            path: /data/cat/data
            type: DirectoryOrCreate
        - name: catool-ns-logs-volume
          hostPath:
            path: /data/cat/logs
            type: DirectoryOrCreate
