apiVersion: v1
kind: Service
metadata:
  name: catool-ns-ws-service
  namespace: catool-ns
  labels:
    app: catool-ns-ws
spec:
  type: NodePort
  selector:
    app: catool-ns-ws
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31472
