apiVersion: v1
kind: Secret
metadata:
  name: complab-secret
  namespace: catool
type: Opaque
data:
  COMPLAB_PASSWORD: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: catool
type: Opaque
data:
  id_rsa: UkVQTEFDRV9NRQ==
