apiVersion: v1
kind: ConfigMap
metadata:
  name: catool-config
  namespace: catool
  labels:
    app: catool
data:
  config.yaml: |
    # Postgres database configuration
    bbn_tool_db: postgresql://admin:F35ygqvr75Z8Wg3qEfgG@catool-postgres-service:5432/catool
    bbn_tool_celery_db: db+postgresql://admin:F35ygqvr75Z8Wg3qEfgG@catool-postgres-service:5432/catool_celery
    celery_queue: amqp://catool-mq-service
    # Workstation Details
    script_dir: /home/complab/tools/catool/scripts
    ssh_user: complab
    display_port: 99
    ldap_auth_enable: false
 