kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: catool-postgres-pv-claim
  namespace: catool
  labels:
    app: catool-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
