apiVersion: v1
kind: ConfigMap
metadata:
  name: catool-ui-config
  namespace: catool-ui
  labels:
    app: catool-ui
data:
  config.js: |
    const CONFIG = {
      mock: false,   //false to use python backend APIs
      baseUrl: 'http://132.186.17.22:30600/',   //backend API URL (direct NodePort)
      apiUrl: 'http://132.186.17.22:30600/',   //backend API url (same as baseUrl, Flask has no /api/ prefix)
      default_lang: 'en-US',   //en-US = English, de-DE = German
      app_version: '0.4.2',
      socket_io_url: 'http://132.186.17.22:31472'   //WebSocket service NodePort
    };
